package sbnz.projekat;
import sbnz.projekat.nutritionadviser.model.*;
import java.util.*;

rule "Find meal that has all groceries"
	 agenda-group "recommendation"
	 when
		 $meal: Meal($allGroceries: getComponents(), $name: name);
		 $pm: PossibleMeals();
		 $gl: GrocerieList($usersGroceries: grocerieList);
		 $usersGroceriesIDS: List() from accumulate (
		 Grocerie($id: id) from $usersGroceries,
			collectList($id)
		 )
		 chechMealGroceries($allGroceries,
		 $usersGroceriesIDS;);
	 then
	 	$pm.getMeals().add($meal);
	end
	
	query chechMealGroceries(List $allGroceries, List $usersGroceriesIDS)
		 $num := Number(intValue == $usersGroceriesIDS.size()) from
			accumulate(Grocerie($id: id, $id memberOf $usersGroceriesIDS) from $allGroceries,
		 init(int count = 0;),
		 action(count += 1;),
		 result(count)
	 )
end